
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-05T15:45:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f534c0a039246dbac9083c1d7280334d4e3fd7d",
 "version": "v2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
